# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:

  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

  - name: Instalar Angular CLI globalmente
    command: npm install -g @angular/cli
    # Se você já tiver o Angular CLI instalado globalmente, remova a linha acima.

  - name: Instalar pacotes de desenvolvimento Angular
    command: npm install --save-dev @angular-devkit/build-angular

  - name: Instalar pacotes de desenvolvimento Angular
    command: npm install --save-dev @angular-devkit/build-angular
  
  - name: Iniciar Gitpod no diretório 'memoteca'
    init: cd memoteca && npm install && ng serve --disable-host-check && npm install -g npm

#  - name: Iniciar JSON Server
 #   command: docker-compose up -d
#    init: docker-compose build   

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 4200 for the frontend
    port: 4200
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
